/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacienteIdRouteImport } from './routes/paciente.$id'
import { Route as PacienteIdEditarRouteImport } from './routes/paciente_.$id.editar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteIdRoute = PacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteIdEditarRoute = PacienteIdEditarRouteImport.update({
  id: '/paciente_/$id/editar',
  path: '/paciente/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/estoque': typeof EstoqueRoute
  '/novo': typeof NovoRoute
  '/pacientes': typeof PacientesRoute
  '/register': typeof RegisterRoute
  '/paciente/$id': typeof PacienteIdRoute
  '/paciente/$id/editar': typeof PacienteIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/estoque': typeof EstoqueRoute
  '/novo': typeof NovoRoute
  '/pacientes': typeof PacientesRoute
  '/register': typeof RegisterRoute
  '/paciente/$id': typeof PacienteIdRoute
  '/paciente/$id/editar': typeof PacienteIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/estoque': typeof EstoqueRoute
  '/novo': typeof NovoRoute
  '/pacientes': typeof PacientesRoute
  '/register': typeof RegisterRoute
  '/paciente/$id': typeof PacienteIdRoute
  '/paciente_/$id/editar': typeof PacienteIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/estoque'
    | '/novo'
    | '/pacientes'
    | '/register'
    | '/paciente/$id'
    | '/paciente/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/estoque'
    | '/novo'
    | '/pacientes'
    | '/register'
    | '/paciente/$id'
    | '/paciente/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/estoque'
    | '/novo'
    | '/pacientes'
    | '/register'
    | '/paciente/$id'
    | '/paciente_/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  EstoqueRoute: typeof EstoqueRoute
  NovoRoute: typeof NovoRoute
  PacientesRoute: typeof PacientesRoute
  RegisterRoute: typeof RegisterRoute
  PacienteIdRoute: typeof PacienteIdRoute
  PacienteIdEditarRoute: typeof PacienteIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/$id': {
      id: '/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/paciente/$id'
      preLoaderRoute: typeof PacienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente_/$id/editar': {
      id: '/paciente_/$id/editar'
      path: '/paciente/$id/editar'
      fullPath: '/paciente/$id/editar'
      preLoaderRoute: typeof PacienteIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  EstoqueRoute: EstoqueRoute,
  NovoRoute: NovoRoute,
  PacientesRoute: PacientesRoute,
  RegisterRoute: RegisterRoute,
  PacienteIdRoute: PacienteIdRoute,
  PacienteIdEditarRoute: PacienteIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
